[project]
name = "mgck"
version = "0.1.0"
description = ""
requires-python = ">=3.10"
authors = [{ name = "badmagick329" }]
license = "MIT"
dependencies = [
    "Django==4.2.17",
    "python-dotenv>=1.0.0,<2",
    "gunicorn>=22.0.0,<23",
    "psycopg2-binary>=2.9.6,<3",
    "requests==2.32.3",
    "beautifulsoup4>=4.12.2,<5",
    "pendulum>=2.1.2,<3",
    "lxml>=4.9.3,<5",
    "praw>=7.7.1,<8",
    "result>=0.13.1,<0.14",
    "djangorestframework>=3.15.2,<4",
    "django-stubs>=4.2.6,<5",
    "djangorestframework-stubs>=3.14.4,<4",
    "django-cors-headers>=4.3.1,<5",
    "drf-yasg>=1.21.7,<2",
]

[tool.hatch.build.targets.wheel]
packages = ["djangobackend"]

[dependency-groups]
dev = [
    "pytest>=7.4.0,<8",
    "pytest-django>=4.5.2,<5",
    "django-stubs>=4.2.4,<5",
    "djangorestframework-stubs>=3.14.5,<4",
    "pytest-watch>=4.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  .*/migrations/*
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.pyright]
include = ["./djangobackend"]
exclude = ["**/node_modules", "**/__pycache__"]
